package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("<style>\n");
      out.write("    .navbar{\n");
      out.write("        position: static;\n");
      out.write("        top: 0;\n");
      out.write("        left: 0;\n");
      out.write("        margin-top: 0px;\n");
      out.write("        padding-top: 0px;\n");
      out.write("        /*sidenav-backdrop-zindex: -9px;*/\n");
      out.write("        background-color: transparent;\n");
      out.write("    }\n");
      out.write("    .nav-item a{\n");
      out.write("        font-size: 25px;\n");
      out.write("        padding: 2px;\n");
      out.write("    }\n");
      out.write("    .nav-item a:hover{\n");
      out.write("        color:skyblue;\n");
      out.write("        /*border-bottom: yellow;*/\n");
      out.write("        margin-bottom: 2px blue;\n");
      out.write("    }\n");
      out.write("    #drop-menu{background-color: black;\n");
      out.write("    }\n");
      out.write("    .dropdown-menu{\n");
      out.write("        z-index: -1;\n");
      out.write("    }\n");
      out.write("    .dropdown-item{\n");
      out.write("        /*z-index: 1px;*/\n");
      out.write("    }\n");
      out.write("    .nav-item{\n");
      out.write("        padding: 5px;\n");
      out.write("        font-size: 20px;\n");
      out.write("        /*z-index:1;*/\n");
      out.write("    }\n");
      out.write("    input:focus{\n");
      out.write("        opacity: 1;\n");
      out.write("        width: 300px;\n");
      out.write("        transition: 2s;\n");
      out.write("    }\n");
      out.write("    #header-container{\n");
      out.write("        min-height: 90vh;\n");
      out.write("        width: 100%;\n");
      out.write("/*        background-image: url('image/girlbackground.jpg');*/\n");
      out.write("        background-repeat: no-repeat;\n");
      out.write("        background-size: cover;\n");
      out.write("        background-position: center;\n");
      out.write("        display: grid;\n");
      out.write("    }\n");
      out.write("    .slider-section{\n");
      out.write("        /*background-image: url('image/girl4.jpg');*/\n");
      out.write("        background-repeat: no-repeat;\n");
      out.write("        background-size: cover;\n");
      out.write("        min-height: 10%;\n");
      out.write("        /*background-position: center;*/\n");
      out.write("        background-position: top 25% right 0;\n");
      out.write("        padding: 0 80px;\n");
      out.write("        padding-top: 0px;\n");
      out.write("        margin-top: 0px;\n");
      out.write("        /*display: grid;*/\n");
      out.write("    }\n");
      out.write("    #slider-content{\n");
      out.write("        margin-top: 13%;\n");
      out.write("    }\n");
      out.write("    #slider-content h4{\n");
      out.write("        padding-bottom: 15px;\n");
      out.write("        color: steelblue;\n");
      out.write("        font-size: 5em;\n");
      out.write("    }\n");
      out.write("    #shop-btn{\n");
      out.write("        /*background-image: url('image/zigzack1.jpeg');*/\n");
      out.write("        border: 1px solid;\n");
      out.write("        width: 140px;\n");
      out.write("        height: 40px;\n");
      out.write("        border-radius: 15px;\n");
      out.write("        color: black;\n");
      out.write("        font-size: 20px;\n");
      out.write("        background-color: lemonchiffon;\n");
      out.write("         margin-left: 20%;\n");
      out.write("    }\n");
      out.write("    #shop-btn:hover{\n");
      out.write("/*        width: 140px;\n");
      out.write("        height: 30px;*/\n");
      out.write("        /*background-color: lemonchiffon;*/\n");
      out.write("        /*margin-top: 2%;*/\n");
      out.write("          box-shadow: 10px 20px 34px rgba(10, 15, 50, 0.3);\n");
      out.write("        transition: 2s;\n");
      out.write("    }\n");
      out.write("    #slider-image-section img{\n");
      out.write("        margin-top: 5%;\n");
      out.write("        height: 550px;\n");
      out.write("        width: 550px;\n");
      out.write("/*        border-radius: 38px;\n");
      out.write("background: #e0e0e0;\n");
      out.write("box-shadow:  17px 17px 34px #8b8b8b,\n");
      out.write("             -17px -17px 34px #ffffff;*/\n");
      out.write("shape-outside: circle(15em at 10% 40%) padding-box;\n");
      out.write("\n");
      out.write("        /*margin-left: 5px;*/\n");
      out.write("        /*clip-path: polygon(0% 15%, 15% 15%, 15% 0%, 85% 0%, 85% 15%, 100% 15%, 100% 85%, 85% 85%, 85% 100%, 15% 100%, 15% 85%, 0% 85%);*/\n");
      out.write(" \n");
      out.write("  aspect-ratio: 1;\n");
      out.write("  /*clip-path: polygon(99.2% 58.89%,89.43% 80.74%,70.63% 95.55%,47.1% 99.92%,24.24% 92.85%,7.27% 75.97%,0.1% 53.14%,4.36% 29.59%,19.07% 10.72%,40.87% 0.84%,64.76% 2.23%,85.27% 14.56%,97.7% 35.01%);*/\n");
      out.write("    }\n");
      out.write("    .slider-section{\n");
      out.write("        /*z-index: -1;*/\n");
      out.write("    } \n");
      out.write("    .li:hover{\n");
      out.write("        border-bottom: 2px solid blue;\n");
      out.write("        transition: 2s;\n");
      out.write("    }\n");
      out.write("/*    #joinus{\n");
      out.write("      border-radius: 22px;\n");
      out.write("background: #ecbbbb;\n");
      out.write("box-shadow: 20px 20px 60px #00000041,inset -20px -20px 23px #ffdddd;\n");
      out.write("    }*/\n");
      out.write("</style>\n");
      out.write("<!--bekar kisheader-->\n");
      out.write("<div class=\"row\">\n");
      out.write("    <nav class=\"navbar navbar-expand-lg\">\n");
      out.write("        <nav class=\"navbar bg-body-tertiary fixed-top\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">Offcanvas navbar</a>\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasNavbar\" aria-controls=\"offcanvasNavbar\" aria-label=\"Toggle navigation\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("    <div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"offcanvasNavbar\" aria-labelledby=\"offcanvasNavbarLabel\">\n");
      out.write("      <div class=\"offcanvas-header\">\n");
      out.write("        <h5 class=\"offcanvas-title\" id=\"offcanvasNavbarLabel\">Offcanvas</h5>\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"offcanvas-body\">\n");
      out.write("        <ul class=\"navbar-nav justify-content-end flex-grow-1 pe-3\">\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Home</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"#\">Link</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("              Dropdown\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"dropdown-menu\">\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\n");
      out.write("              <li>\n");
      out.write("                <hr class=\"dropdown-divider\">\n");
      out.write("              </li>\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <form class=\"d-flex mt-3\" role=\"search\">\n");
      out.write("          <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("          <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("    </nav>\n");
      out.write("</div>\n");
      out.write("<!--bekar ka nevbar end-->\n");
      out.write("<div class=\"row\">\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light bg-body-tertiary\">\n");
      out.write("  <!-- Container wrapper -->\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <!-- Toggle button -->\n");
      out.write("    <button\n");
      out.write("      data-mdb-collapse-init\n");
      out.write("      class=\"navbar-toggler\"\n");
      out.write("      type=\"button\"\n");
      out.write("      data-mdb-target=\"#navbarLeftAlignExample\"\n");
      out.write("      aria-controls=\"navbarLeftAlignExample\"\n");
      out.write("      aria-expanded=\"false\"\n");
      out.write("      aria-label=\"Toggle navigation\"\n");
      out.write("    >\n");
      out.write("      <i class=\"fas fa-bars\"></i>\n");
      out.write("    </button>\n");
      out.write("\n");
      out.write("    <!-- Collapsible wrapper -->\n");
      out.write("    <div class=\"collapse navbar-collapse \" id=\"navbarLeftAlignExample\">\n");
      out.write("      <!-- Left links -->\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("        <li class=\"nav-item li\">\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Home</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item li\">\n");
      out.write("            <a class=\"nav-link\" href=\"about.jsp\">About Us</a>\n");
      out.write("        </li>\n");
      out.write("        <!-- Navbar dropdown -->\n");
      out.write("        <li class=\"nav-item li\">\n");
      out.write("          <a data-mdb-dropdown-init class=\"nav-link\" href=\"product.jsp\">\n");
      out.write("            Product\n");
      out.write("          </a>\n");
      out.write("      \n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("      <!-- Left links -->\n");
      out.write("        <form class=\"d-flex\" role=\"search\" style=\"margin:auto; width: 400px; border-radius: 50px;\">\n");
      out.write("            <input title=\"seach\" class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" style=\"border-radius: 50px;\">\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\" style=\"border-radius: 50%;\"><i class=\"fa-brands fa-searchengin\"></i></button>\n");
      out.write("      </form>\n");
      out.write("      <a href=\"registration.jsp\"><button  title=\"register yourself\"class=\"btn btn-outline-info\" type=\"submit\" style=\"margin-right:10px; border-radius: 50%;\"><i class=\"fa-solid fa-book-open-reader\"></i></button></a>\n");
      out.write("        &nbsp;\n");
      out.write("        <a href=\"login.jsp\"><button title=\"login\" class=\"btn btn-outline-warning\" type=\"submit\" style=\"margin-right: 150px; border-radius: 50%;\"><i class=\"fa-solid fa-user-pen\" style=\"color: #083d44;\"></i></i></button></a>\n");
      out.write("    </div>\n");
      out.write("    <a href=\"joinus.jsp\"> <button  type=\"button\" id=\"joinus\" class=\"btn trigger\" data-bs-toggle=\"modal\" data-bs-target=\"#staticBackdrop\"style=\" border-radius:150px;\">\n");
      out.write("    <!--<i class=\"fa-solid fa-book-open-reader\">-->\n");
      out.write("        join us\n");
      out.write("    \n");
      out.write("</button>\n");
      out.write("    </a>\n");
      out.write("    ");
      out.write("\n");
      out.write("    <i class=\"fas fa-sun\"></i>&nbsp; &nbsp;\n");
      out.write("    <div class=\"form-check form-switch\">\n");
      out.write("            <input class=\"form-check-input p-2\" type=\"checkbox\" role=\"switch\" id=\"flexSwitchCheckChecked\" checked onclick=\"myfunction()\"/>\n");
      out.write("        </div>\n");
      out.write("    <i class=\"fas fa-moon\"></i>\n");
      out.write("  </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <!-- Collapsible wrapper -->\n");
      out.write("  <!-- Container wrapper -->\n");
      out.write("</nav>\n");
      out.write("  </div>\n");
      out.write("<!--Slider sectiom-->\n");
      out.write("<section class=\"slider-section\" style=\"min-height: 700px; min-width: 10%;\">\n");
      out.write("    <div class=\"row\" >\n");
      out.write("        <div class=\"col-sm-5\" id=\"slider-content\">\n");
      out.write("            <h4> Trade-in-offer</h4>\n");
      out.write("            <h1 style=\"padding-left: 30px;\">Super value deals</h1>\n");
      out.write("            <h1 style=\"padding-left: 30px; color: seagreen;\">Cosmetics All Products</h1>\n");
      out.write("            <p style=\"padding-left: 40px; font-size: 20px; font-weight: bolder;\">Save more with coupons & up to 70% off!</p>\n");
      out.write("            <button  type=\"button\"id='shop-btn'>Shop Now</button>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-sm-7\">\n");
      out.write("            <section id=\"slider-image-section\">\n");
      out.write("                <center><img src=\"https://source.unsplash.com/random/\"style=\"margin-left: 0;\" data-aos=\"fade-up\"data-aos-duration=\"2000\"></center>\n");
      out.write("                <!--<img src=\"image/slider-girl.png\"style=\"margin-left: 0;\"style=\"z-index: -10; margin-left: 15%;\">-->\n");
      out.write("            </section>\n");
      out.write("        </div>\n");
      out.write("            </div>\n");
      out.write("</section>\n");
      out.write("<script>\n");
      out.write("    const themeStitcher = document.getElementById(\"themingSwitcher\");\n");
      out.write("const isSystemThemeSetToDark = window.matchMedia(\"(prefers-color-scheme: dark)\").matches;\n");
      out.write("\n");
      out.write("// set toggler position based on system theme\n");
      out.write("if (isSystemThemeSetToDark) {\n");
      out.write("  themeStitcher.checked = true;\n");
      out.write("}\n");
      out.write("\n");
      out.write("// add listener to theme toggler\n");
      out.write("themeStitcher.addEventListener(\"change\", (e) => {\n");
      out.write("  toggleTheme(e.target.checked);\n");
      out.write("});\n");
      out.write("\n");
      out.write("const toggleTheme = (isChecked) => {\n");
      out.write("  const theme = isChecked ? \"dark\" : \"light\";\n");
      out.write("\n");
      out.write("  document.documentElement.dataset.mdbTheme = theme;\n");
      out.write("}\n");
      out.write("\n");
      out.write("// add listener to toggle theme with Shift + D\n");
      out.write("document.addEventListener(\"keydown\", (e) => {\n");
      out.write("  if (e.shiftKey && e.key === \"D\") {\n");
      out.write("    themeStitcher.checked = !themeStitcher.checked;\n");
      out.write("    toggleTheme(themeStitcher.checked);\n");
      out.write("  }\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("  const isSystemThemeSetToDark = window.matchMedia(\"(prefers-color-scheme: dark)\").matches;\n");
      out.write("\n");
      out.write("  if (isSystemThemeSetToDark) {\n");
      out.write("    document.documentElement.dataset.mdbTheme = \"dark\";\n");
      out.write("  };\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--Navbar End-->\n");
      out.write("<!-- Slider Start-->\n");
      out.write("<!--Slider left side for images--> \n");
      out.write("\n");
      out.write("<!--Products End-->");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
