package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>H2H Groups Private Limited India</title>\n");
      out.write("        <link href=\"css/bootstrap.css\" rel=\"stylesheet\"/>\n");
      out.write("        <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\" integrity=\"sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("        <script src=\"js/bootstrap.bundle.js\"></script>\n");
      out.write("        <link rel=\"stylesheet\"href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\"/>\n");
      out.write("        <link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"css/index-style.css\" rel=\"stylesheet\"/>\n");
      out.write("        <link rel=\"website icon\" type=\"png\" href=\"image/h2hlogop.png\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <style>\n");
      out.write("      #imagepara{\n");
      out.write("            font-size: 30px;\n");
      out.write("            margin-top: 2px;\n");
      out.write("            margin: auto;\n");
      out.write("            z-index: 1px;\n");
      out.write("        }\n");
      out.write("        .about-banner{\n");
      out.write("            display: grid;\n");
      out.write("        }\n");
      out.write("        .about-banner img{\n");
      out.write("            filter:blur(0px);\n");
      out.write("            box-shadow: 10px 20px 34px rgba(10, 15, 50, 0.3);\n");
      out.write("            border-radius: 24px 3px 6px 8px;\n");
      out.write("        }\n");
      out.write("        .gallery-image{\n");
      out.write("            filter:grayscale(100%);\n");
      out.write("        }\n");
      out.write("        .gallery-image:hover{\n");
      out.write("            transform: rotate(30deg);\n");
      out.write("            border-radius: 25px;\n");
      out.write("            filter: drop-shadow(10px 7px 10px red);\n");
      out.write("        }\n");
      out.write("        .about-banner{\n");
      out.write("            transform: rotate(20deg);\n");
      out.write("        }\n");
      out.write("        .about-contenet{\n");
      out.write("            \n");
      out.write("        }\n");
      out.write("        .choice-button{\n");
      out.write("  transform: rotate(-25deg) skew(25deg);\n");
      out.write("  transform-style: preserve-3d;\n");
      out.write("  /*position: relative;*/\n");
      out.write("  list-style: none;\n");
      out.write("  width: 100px;\n");
      out.write("  height: 32px;\n");
      out.write("  border: none;\n");
      out.write("  background: transparent;\n");
      out.write("  font-family: inherit;\n");
      out.write("  cursor: pointer;\n");
      out.write("}\n");
      out.write("#Read{\n");
      out.write("    margin-top:50px;\n");
      out.write("    margin-left:200px;\n");
      out.write("}\n");
      out.write(".choice-button:before {\n");
      out.write("  content: '';\n");
      out.write("  position: absolute;\n");
      out.write("  bottom: -10px;\n");
      out.write("  left: -5px;\n");
      out.write("  width: 100%;\n");
      out.write("  height: 10px;\n");
      out.write("  background: #2a2a2a;\n");
      out.write("  transform: skewX(-41deg);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:after {\n");
      out.write("  content: '';\n");
      out.write("  position: absolute;\n");
      out.write("  top: 5px;\n");
      out.write("  left: -9px;\n");
      out.write("  width: 9px;\n");
      out.write("  height: 100%;\n");
      out.write("  background: #2a2a2a;\n");
      out.write("  transform: skewY(-49deg);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button span {\n");
      out.write("  position: absolute;\n");
      out.write("  top: 0;\n");
      out.write("  left: 0;\n");
      out.write("  width: 100%;\n");
      out.write("  height: 100%;\n");
      out.write("  background: #2a2a2a;\n");
      out.write("  color: #fff;\n");
      out.write("  font-size: 25px;\n");
      out.write("  transition: 1.1s ease-out;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:hover span {\n");
      out.write("  z-index: 1000;\n");
      out.write("  transition: .3s;\n");
      out.write("  color: yellow;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:hover span:nth-child(5) {\n");
      out.write("  transform: translate(40px, -40px);\n");
      out.write("  opacity: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:hover span:nth-child(4) {\n");
      out.write("  transform: translate(30px, -30px);\n");
      out.write("  opacity: .8;\n");
      out.write("  background-color: yellow;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:hover span:nth-child(3) {\n");
      out.write("  transform: translate(20px, -20px);\n");
      out.write("  opacity: .6;\n");
      out.write("  background-color: yellow;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:hover span:nth-child(2) {\n");
      out.write("  transform: translate(10px, -10px);\n");
      out.write("  opacity: .4;\n");
      out.write("  background-color: yellow;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:hover span:nth-child(1) {\n");
      out.write("  transform: translate(0px, 0px);\n");
      out.write("  opacity: .2;\n");
      out.write("  background-color: yellow;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:active span:nth-child(5) {\n");
      out.write("  transform: translate(20px, -20px);\n");
      out.write("  opacity: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:active span:nth-child(4) {\n");
      out.write("  transform: translate(15px, -15px);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:active span:nth-child(3) {\n");
      out.write("  transform: translate(10px, -10px);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:active span:nth-child(2) {\n");
      out.write("  transform: translate(5px, -5px);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:active span:nth-child(1) {\n");
      out.write("  transform: translate(0px, 0px);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".choice-button:nth-child(1):hover span {\n");
      out.write("  background: #52E19F;\n");
      out.write("}\n");
      out.write("        body::-webkit-scrollbar{\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        .our-goal-image img{\n");
      out.write("            height: 200px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <body>\n");
      out.write("<!--        <div class=\"form-check form-switch\">\n");
      out.write("            <input class=\"form-check-input p-2\" type=\"checkbox\" role=\"switch\" id=\"flexSwitchCheckChecked\" checked onclick=\"myfunction()\"/>\n");
      out.write("        </div>-->\n");
      out.write("<!--<div id=\"preloader\">\n");
      out.write("    \n");
      out.write("</div>-->\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <!--slider Start-->\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("           \n");
      out.write("            <!--Slider End-->\n");
      out.write("            <!--Feature section start-->\n");
      out.write("            <div class=\"container\">\n");
      out.write("            <section class=\"feautre-section\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-sm-2 mt-3\" id=\"feaute-box\" data-aos=\"fade-left\"data-aos-duration=\"4000\">\n");
      out.write("                        <img src=\"image/feautre-logo3.jpg\" id=\"feaute-product-logo\">\n");
      out.write("                        <h6 id=\"feaute-box1\"> Free Shipping</h6>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-2 mt-3\" id=\"feaute-box\" data-aos=\"fade-left\"data-aos-duration=\"5000\">\n");
      out.write("                        <img src=\"image/feautre-logo2.jpg\" id=\"feaute-product-logo\">\n");
      out.write("                        <h6 id=\"feaute-box2\">100% Testing</h6>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-2 mt-3\" id=\"feaute-box\" data-aos=\"fade-left\"data-aos-duration=\"6000\">\n");
      out.write("                        <img src=\"image/feautre-logo1.jpg\" id=\"feaute-product-logo\">\n");
      out.write("                        <h6 id=\"feaute-box3\">Organic</h6>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-2 mt-3\" id=\"feaute-box\" data-aos=\"fade-left\"data-aos-duration=\"7000\">\n");
      out.write("                        <img src=\"image/feautre-logo4.jpg\" id=\"feaute-product-logo\">\n");
      out.write("                        <h6 id=\"feaute-box4\">On Time Delivery</h6>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-2 mt-3\" id=\"feaute-box\" data-aos=\"fade-left\"data-aos-duration=\"8000\">\n");
      out.write("                        <img src=\"image/feautre-logo5.jpg\" id=\"feaute-product-logo\">\n");
      out.write("                        <h6 id=\"feaute-box5\">High Quality Product</h6>\n");
      out.write("                    </div>\n");
      out.write("                    <!--<div class=\"col-sm-2\" id=\"feaute-box\">6</div>-->\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("            </div>\n");
      out.write("            <!--feautr section end-->\n");
      out.write("            <!--Trending product-->\n");
      out.write("            <!--<section id=\"trend\" style=\"min-height:700px;\">-->\n");
      out.write("            <div class=\"container-fluid\" style=\"\">\n");
      out.write("            <div class=\"row mt-1\">\n");
      out.write("                <div class=\"col-sm-12 animate__animated animate__bounce\" style=\"min-height: 300px;  background-color: #94A7E;\">\n");
      out.write("                    <h2 style=\"margin-left: 15px; margin-top: 80px; font-size:3rem;text-align: center;\">TRENDING RIGHT NOW</h2>\n");
      out.write("\n");
      out.write("                    <p style=\"margin-top:20px;  margin-left: 10px; font-family: serif; font-weight: bold; font-size: 30px;text-align:center;\">Looking for something specific? Shop by category to find your perfect piece of Beauty!</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row mt-3\">\n");
      out.write("                    <div class=\"col-sm-3 text-center\" data-aos=\"fadeInTopright\"data-aos-duration=\"5000\">\n");
      out.write("                        <div class=\"section shadow-lg\">\n");
      out.write("                            <img src=\"image/sl1.jpg\" alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("                        <button type=\"button\" class=\"btn btn-warning mt-5\">Visit Now</button>\n");
      out.write("                    </div>\n");
      out.write("                     <div class=\"col-sm-3 text-center\">\n");
      out.write("                        <div class=\"section shadow-lg\">\n");
      out.write("                            <img src=\"image/sl2.jpg\" alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("                         <button type=\"button\" class=\"btn btn-warning mt-5\">Visit Now</button>\n");
      out.write("                    </div>\n");
      out.write("                     <div class=\"col-sm-3 text-center\">\n");
      out.write("                        <div class=\"section shadow-lg\">\n");
      out.write("                            <img src=\"image/sl3.jpg\" alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("                         <button type=\"button\" class=\"btn btn-warning mt-5\">Visit Now</button>\n");
      out.write("                    </div>\n");
      out.write("                     <div class=\"col-sm-3 text-center\">\n");
      out.write("                        <div class=\"section shadow-lg\">\n");
      out.write("                            <img src=\"image/sl4.jpg\" alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("                         <button type=\"button\" class=\"btn btn-warning mt-5\">Visit Now</button>\n");
      out.write("                    </div>\n");
      out.write("                   </div>\n");
      out.write("              </div>\n");
      out.write("             </div>\n");
      out.write("            <!--</section>-->\n");
      out.write("            <!--Recommendation Section-->\n");
      out.write("            <div class=\"row mt-4\">\n");
      out.write("                <div class=\"col-sm-12\" >\n");
      out.write("                    <h2 style=\"margin-top:25px;  margin-left: 10px; font-family: serif; font-weight: bold; font-size: 47px;text-align:center;\">Featured Products</h2>\n");
      out.write("                    <p style=\"margin-top:20px;  margin-left: 10px; font-family: serif; font-weight: bold; font-size: 45px;text-align:center; color: steelblue\">Products Collection For Your All Skin Care</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <section class=\"feature-product\">\n");
      out.write("                    <!--Product Row-1-->\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                       <div class=\"col-sm-3\" id=\"product-image\" style=\"margin: 10px;\" data-aos=\"fade-up\"data-aos-duration=\"3000\">\n");
      out.write("                           <img src=\"image/face-wash1-removebg-preview.png\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                                <span>H2H Groups </span>\n");
      out.write("                                <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        </a>\n");
      out.write("                        <div class=\"col-sm-3\" id=\"product-image\" style=\"margin: 10px;\" data-aos=\"fade-up\"data-aos-duration=\"3000\">\n");
      out.write("                                 <img src=\"image/toner-removebg-preview.png\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                               <a href=\"alovera-facewash.jsp\" style=\"text-decoration: none; color: black;\">   <span>H2H Groups </span>\n");
      out.write("                                 <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                               </a>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-3\" id=\"product-image\" style=\"margin: 10px;\" data-aos=\"fade-up\"data-aos-duration=\"3000\">\n");
      out.write("                             <img src=\"image/product cho3.jpg\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                                <span>H2H Groups </span>\n");
      out.write("                                <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-3\"id=\"product-image\" style=\"margin: 10px;\" data-aos=\"fade-up\"data-aos-duration=\"3000\">\n");
      out.write("                             <img src=\"image/product cho4.jpg\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                                <span>H2H Groups </span>\n");
      out.write("                                <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div> \n");
      out.write("                    <!--Product row-2-->\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-sm-3\" id=\"product-image\" style=\"margin: 1px;\" data-aos=\"fade-up\" data-aos-duration=\"3000\">\n");
      out.write("                            <img src=\"image/product cho4.jpg\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                                <span>H2H Groups </span>\n");
      out.write("                                <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-3\" id=\"product-image\" style=\"margin: 10px;\" data-aos=\"fade-up\"data-aos-duration=\"3000\">\n");
      out.write("                             <img src=\"image/product cho3.jpg\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                                <span>H2H Groups </span>\n");
      out.write("                                <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-3\" id=\"product-image\" style=\"margin: 10px;\" data-aos=\"fade-up\"data-aos-duration=\"3000\">\n");
      out.write("                            <img src=\"image/product_cho2-removebg-preview.png\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                                <span>H2H Groups </span>\n");
      out.write("                                <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-3\"id=\"product-image\" style=\"margin: 10px;\" data-aos=\"fade-up\"data-aos-duration=\"3000\">\n");
      out.write("                             <img src=\"image/product cho1.jpg\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                                <span>H2H Groups </span>\n");
      out.write("                                <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!--Product Row-3-->\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-sm-3\" id=\"product-image\" style=\"margin: 10px;\" data-aos=\"fade-up\"data-aos-duration=\"3000\">\n");
      out.write("                            <img src=\"image/product cho1.jpg\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                                <span>H2H Groups </span>\n");
      out.write("                                <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-3\" id=\"product-image\" style=\"margin: 10px;\" data-aos=\"fade-up\"data-aos-duration=\"3000\">\n");
      out.write("                             <img src=\"image/product cho2.jpg\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                                <span>H2H Groups </span>\n");
      out.write("                                <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-3\" id=\"product-image\" style=\"margin: 10px;\" data-aos=\"fade-up\"data-aos-duration=\"3000\">\n");
      out.write("                             <img src=\"image/product cho3.jpg\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                                <span>H2H Groups </span>\n");
      out.write("                                <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-3\"id=\"product-image\" style=\"margin: 10px;\" data-aos=\"fade-up\"data-aos-duration=\"3000\">\n");
      out.write("                             <img src=\"image/product cho4.jpg\" alt=\"\" style=\"width: 100%; height: 300px; border-radius: 10px;\">\n");
      out.write("                            <div class=\"des\">\n");
      out.write("                                <span>H2H Groups </span>\n");
      out.write("                                <h5>Alovera Face Wash</h5>\n");
      out.write("                                <div class=\"star\">\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                    <i class=\"fas fa-star\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <h4>$80</h4>\n");
      out.write("                                <!--<a href=\"#\"><i class=\"fa-solid fa-cart-shopping cart\" style=\"color: #053325;\"></i></a>-->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </section>\n");
      out.write("            </div>\n");
      out.write("            <!--About us section start-->\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("            <div class=\"about-container\" style=\"display:grid; grid-gap:10px;\">\n");
      out.write("            <div class=\"row\" style=\"min-height: 500px; border: ; margin-top: 5%;\">\n");
      out.write("                <div class=\"col-sm-6 mt-3\">\n");
      out.write("                    <div class=\"about-banner\">\n");
      out.write("                        <img src=\"https://source.unsplash.com/random/\"  style=\"height: 400px; width: 400px; border-radius: none; margin-left: 20%;\" data-aos=\"fade-left\"data-aos-duration=\"2000\">\n");
      out.write("                    </div>\n");
      out.write("                </div> \n");
      out.write("                <div class=\"col-6 mt-3 ml-5\">\n");
      out.write("                    <div class=\"about-text\" style=\"min-height: 450px; width: 70%; background-color: ; margin-top: 2%; margin-right: 10%;\">\n");
      out.write("                        <h1 style=\"margin-top: 12px; text-align: center;\"><span style=\"color: yellow;\">About</span> Us</h1>\n");
      out.write("                        <h2 mx-5>Why choose us ?</h2>\n");
      out.write("                        <p style=\"margin: auto; line-height: 30px; font-size: 20px; margin-left: 15px; margin-top: 5%;\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio libero vitae quisquam facilis, voluptatibus cumque quis sint laudantium itaque, id dolorem mollitia magnam, ducimus quos? Excepturi qui et necessitatibus molestias itaque. Suscipit, perferendis iusto. Sed, error adipisci? Unde asperiores quo repellendus ad voluptatem dolores, ducimus ipsa quisquam consectetur officia exercitationem?</p>\n");
      out.write("                        <a href=\"about.jsp\">                          <br>\n");
      out.write("                      <button id=\"Read\" class=\"choice-button\">\n");
      out.write("  <span></span>\n");
      out.write("  <span></span>\n");
      out.write("  <span></span>\n");
      out.write("  <span></span>\n");
      out.write("  <span>More <span style=\"color:white;\">Read </span>\n");
      out.write("</button>\n");
      out.write("                        </a>\n");
      out.write("                        <!--<button type=\"btn\" class=\"btn btn-warning\" style=\"margin-left: 15%; margin-top: 5%; height: 45px; width: 150px; border-radius: 10px;\"> Read More</button>-->\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("            <!--About Us section End-->\n");
      out.write("           \n");
      out.write("         \n");
      out.write("            <!--Our Gallery Start-->\n");
      out.write("            \n");
      out.write("            <div class=\"container\" style=\"display: grid; grid-gap:10px;\"> \n");
      out.write("               <div  class=\"row about-contenet\">\n");
      out.write("               <h2 style=\"text-align: center; font-size: 50px; color: crimson;\">Our Gallery</h2>\n");
      out.write("               <p style=\"font-weight: bold; color: steelblue;\">\n");
      out.write("                   Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio libero vitae quisquam facilis, voluptatibus cumque quis sint laudantium itaque, id dolorem mollitia magnam, ducimus quos? Excepturi qui et necessitatibus molestias itaque. Suscipit, perferendis iusto. Sed, error adipisci? Unde asperiores quo repellendus ad vol\n");
      out.write("               </p>\n");
      out.write("               </div>\n");
      out.write("               <div class=\"row mt-2\">\n");
      out.write("                   <div class=\"col-sm-4 gallery-image\">\n");
      out.write("                       <img src=\"image/girl1.jpg\" style=\"margin-left: 25%;\" data-aos=\"fade-down\"data-aos-duration=\"1700\">\n");
      out.write("                       <p id=\"imagepara\"></p>\n");
      out.write("                   </div>\n");
      out.write("                   <div class=\"col-sm-4 gallery-image\">\n");
      out.write("                       <img src=\"image/girl2.jpg\" style=\"margin-left: 25%;\" data-aos=\"fade-down\"data-aos-duration=\"1750\">\n");
      out.write("                   </div>\n");
      out.write("                   <div class=\"col-sm-4 gallery-image\">\n");
      out.write("                       <img src=\"image/girl3.jpg\" style=\"margin-left: 25%;\" data-aos=\"fade-down\"data-aos-duration=\"1800\">\n");
      out.write("                   </div>\n");
      out.write("               </div>\n");
      out.write("               <div class=\"row mt-2\">\n");
      out.write("                   <div class=\"col-sm-4 gallery-image\">\n");
      out.write("                       <img src=\"image/girl4.jpg\" data-aos=\"fade-down\"data-aos-duration=\"1900\">\n");
      out.write("                   </div>\n");
      out.write("                   <div class=\"col-sm-4 gallery-image\">\n");
      out.write("                       <img src=\"image/girl5.jpg\" data-aos=\"fade-down\"data-aos-duration=\"1950\" style=\"filter:blur;\">\n");
      out.write("                   </div>\n");
      out.write("                   <div class=\"col-sm-4 gallery-image\">\n");
      out.write("                       <img src=\"image/girl6.jpg\" data-aos=\"fade-down\"data-aos-duration=\"2000\">\n");
      out.write("                   </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <br>\n");
      out.write("            <hr style=\"height: 15px; color: blue; width: 20%; margin-left:35%;\">\n");
      out.write("            <hr style=\"height: 15px; color: darkorchid;\">\n");
      out.write("            <hr style=\"height: 15px; color: blue;\">\n");
      out.write("            <!--Our Galary End-->\n");
      out.write("          <!--our goal start-->\n");
      out.write("          <div class=\"container mt-3\" style=\"disply:grid; grid-gap:10px;\">\n");
      out.write("              <div class=\"row mt-5\">\n");
      out.write("                  <div class=\"col-7\">\n");
      out.write("                      <h3 style=\"margin-top: 15px;\">Our Goal</h3>\n");
      out.write("                      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio libero vitae quisquam facilis, voluptatibus cumque quis sint laudantium itaque, id dolorem mollitia magnam, ducimus quos? Excepturi qui et necessitatibus molestias itaque. Suscipit, perferendis iusto. Sed, error adipisci? Unde asperiores quo repelle</p>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-5\">\n");
      out.write("                      <img src=\"image/girlbackground.jpg\" style=\"height:400px; width: 400px; margin-left: 15%; filter: drop-shadow(10px 7px 10px orange); transform: scale();\">\n");
      out.write("                  </div>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("              <!--our goal end-->\n");
      out.write("        <!--Qualities product-->\n");
      out.write("\n");
      out.write("        <!--Container End-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("          <!--Dark-light Mode javaScript Code-->\n");
      out.write("     <script>\n");
      out.write("         function myfunction(){\n");
      out.write("             var element = document.body;\n");
      out.write("             element.dataset.bsTheme = \n");
      out.write("                     element.dataset.bsTheme == \"light\" ? \"dark\": \"light\";\n");
      out.write("             }\n");
      out.write("         </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("        <!--Animation Script-->\n");
      out.write("        <script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\n");
      out.write("        <script>\n");
      out.write("            AOS.init();\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
