package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class slider_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Document</title>\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("    html, body {\n");
      out.write("    overflow: hidden;\n");
      out.write("    padding: 0;\n");
      out.write("    margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("canvas {\n");
      out.write("    position: fixed;\n");
      out.write("    top: 0;\n");
      out.write("    left: 0;\n");
      out.write("    width: 100%;\n");
      out.write("    height: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content {\n");
      out.write("    position: fixed;\n");
      out.write("    top: 0;\n");
      out.write("    left: 0;\n");
      out.write("    width: 100%;\n");
      out.write("    height: 100vh;\n");
      out.write("}\n");
      out.write("\n");
      out.write("img {\n");
      out.write("    position: absolute;\n");
      out.write("    top: 50%;\n");
      out.write("    left: 50%;\n");
      out.write("    transform: translate(-50%, -50%);\n");
      out.write("    height: 115%;\n");
      out.write("    width: auto;\n");
      out.write("    opacity: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (min-aspect-ratio: 4/3) {\n");
      out.write("    img {\n");
      out.write("        height: auto;\n");
      out.write("        width: 100%;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (max-aspect-ratio: 3/5) {\n");
      out.write("    img {\n");
      out.write("        left: 30%;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write(".overlay {\n");
      out.write("    position: fixed;\n");
      out.write("    top: 50%;\n");
      out.write("    left: 30%;\n");
      out.write("    max-width: 50%;\n");
      out.write("    transform: translate(-50%, -50%);\n");
      out.write("    font-family: sans-serif;\n");
      out.write("    font-size: 10vh;\n");
      out.write("    font-weight: bold;\n");
      out.write("    pointer-events: none;\n");
      out.write("    text-transform: uppercase;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (max-aspect-ratio: 1/1) {\n");
      out.write("    .overlay {\n");
      out.write("        left: 50%;\n");
      out.write("        width: 90%;\n");
      out.write("        max-width: 90%;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (max-aspect-ratio: 3/5) {\n");
      out.write("    .overlay {\n");
      out.write("        font-size: 5vh;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("    <div class=\"content\">\n");
      out.write("        <img src=\"https://ksenia-k.com/img/ksenia.jpg\"/>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <canvas></canvas>\n");
      out.write("    \n");
      out.write("    <div class=\"overlay\">\n");
      out.write("        <h1>H2H</h1>\n");
      out.write("        <h5>Transforming your visions into Reality</h5>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <script type=\"x-shader/x-fragment\" id=\"vertShader\">\n");
      out.write("        precision highp float;\n");
      out.write("    \n");
      out.write("        attribute vec2 aPosition;\n");
      out.write("        varying vec2 vUv;\n");
      out.write("        varying vec2 vL;\n");
      out.write("        varying vec2 vR;\n");
      out.write("        varying vec2 vT;\n");
      out.write("        varying vec2 vB;\n");
      out.write("        uniform vec2 u_vertex_texel;\n");
      out.write("    \n");
      out.write("        void main () {\n");
      out.write("            vUv = aPosition * .5 + .5;\n");
      out.write("            vL = vUv - vec2(u_vertex_texel.x, 0.);\n");
      out.write("            vR = vUv + vec2(u_vertex_texel.x, 0.);\n");
      out.write("            vT = vUv + vec2(0., u_vertex_texel.y);\n");
      out.write("            vB = vUv - vec2(0., u_vertex_texel.y);\n");
      out.write("            gl_Position = vec4(aPosition, 0., 1.);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("    <script type=\"x-shader/x-fragment\" id=\"fragShaderAdvection\">\n");
      out.write("        precision highp float;\n");
      out.write("        precision highp sampler2D;\n");
      out.write("    \n");
      out.write("        varying vec2 vUv;\n");
      out.write("        uniform sampler2D u_velocity_txr;\n");
      out.write("        uniform sampler2D u_input_txr;\n");
      out.write("        uniform vec2 u_vertex_texel;\n");
      out.write("        uniform vec2 u_output_textel;\n");
      out.write("        uniform float u_dt;\n");
      out.write("        uniform float u_dissipation;\n");
      out.write("    \n");
      out.write("        vec4 bilerp (sampler2D sam, vec2 uv, vec2 tsize) {\n");
      out.write("            vec2 st = uv / tsize - 0.5;\n");
      out.write("    \n");
      out.write("            vec2 iuv = floor(st);\n");
      out.write("            vec2 fuv = fract(st);\n");
      out.write("    \n");
      out.write("            vec4 a = texture2D(sam, (iuv + vec2(0.5, 0.5)) * tsize);\n");
      out.write("            vec4 b = texture2D(sam, (iuv + vec2(1.5, 0.5)) * tsize);\n");
      out.write("            vec4 c = texture2D(sam, (iuv + vec2(0.5, 1.5)) * tsize);\n");
      out.write("            vec4 d = texture2D(sam, (iuv + vec2(1.5, 1.5)) * tsize);\n");
      out.write("    \n");
      out.write("            return mix(mix(a, b, fuv.x), mix(c, d, fuv.x), fuv.y);\n");
      out.write("        }\n");
      out.write("    \n");
      out.write("        void main () {\n");
      out.write("            vec2 coord = vUv - u_dt * bilerp(u_velocity_txr, vUv, u_vertex_texel).xy * u_vertex_texel;\n");
      out.write("            gl_FragColor = u_dissipation * bilerp(u_input_txr, coord, u_output_textel);\n");
      out.write("            gl_FragColor.a = 1.;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("    <script type=\"x-shader/x-fragment\" id=\"fragShaderDivergence\">\n");
      out.write("        precision highp float;\n");
      out.write("        precision highp sampler2D;\n");
      out.write("    \n");
      out.write("        varying highp vec2 vUv;\n");
      out.write("        varying highp vec2 vL;\n");
      out.write("        varying highp vec2 vR;\n");
      out.write("        varying highp vec2 vT;\n");
      out.write("        varying highp vec2 vB;\n");
      out.write("        uniform sampler2D u_velocity_txr;\n");
      out.write("    \n");
      out.write("        void main () {\n");
      out.write("            float L = texture2D(u_velocity_txr, vL).x;\n");
      out.write("            float R = texture2D(u_velocity_txr, vR).x;\n");
      out.write("            float T = texture2D(u_velocity_txr, vT).y;\n");
      out.write("            float B = texture2D(u_velocity_txr, vB).y;\n");
      out.write("    \n");
      out.write("            float div = .5 * (R - L + T - B);\n");
      out.write("            gl_FragColor = vec4(div, 0., 0., 1.);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("    <script type=\"x-shader/x-fragment\" id=\"fragShaderPressure\">\n");
      out.write("        precision highp float;\n");
      out.write("        precision highp sampler2D;\n");
      out.write("    \n");
      out.write("        varying highp vec2 vUv;\n");
      out.write("        varying highp vec2 vL;\n");
      out.write("        varying highp vec2 vR;\n");
      out.write("        varying highp vec2 vT;\n");
      out.write("        varying highp vec2 vB;\n");
      out.write("        uniform sampler2D u_pressure_txr;\n");
      out.write("        uniform sampler2D u_divergence_txr;\n");
      out.write("    \n");
      out.write("        void main () {\n");
      out.write("            float L = texture2D(u_pressure_txr, vL).x;\n");
      out.write("            float R = texture2D(u_pressure_txr, vR).x;\n");
      out.write("            float T = texture2D(u_pressure_txr, vT).x;\n");
      out.write("            float B = texture2D(u_pressure_txr, vB).x;\n");
      out.write("            float C = texture2D(u_pressure_txr, vUv).x;\n");
      out.write("            float divergence = texture2D(u_divergence_txr, vUv).x;\n");
      out.write("            float pressure = (L + R + B + T - divergence) * 0.25;\n");
      out.write("            gl_FragColor = vec4(pressure, 0., 0., 1.);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("    <script type=\"x-shader/x-fragment\" id=\"fragShaderGradientSubtract\">\n");
      out.write("        precision highp float;\n");
      out.write("        precision highp sampler2D;\n");
      out.write("    \n");
      out.write("        varying highp vec2 vUv;\n");
      out.write("        varying highp vec2 vL;\n");
      out.write("        varying highp vec2 vR;\n");
      out.write("        varying highp vec2 vT;\n");
      out.write("        varying highp vec2 vB;\n");
      out.write("        uniform sampler2D u_pressure_txr;\n");
      out.write("        uniform sampler2D u_velocity_txr;\n");
      out.write("    \n");
      out.write("        void main () {\n");
      out.write("            float L = texture2D(u_pressure_txr, vL).x;\n");
      out.write("            float R = texture2D(u_pressure_txr, vR).x;\n");
      out.write("            float T = texture2D(u_pressure_txr, vT).x;\n");
      out.write("            float B = texture2D(u_pressure_txr, vB).x;\n");
      out.write("            vec2 velocity = texture2D(u_velocity_txr, vUv).xy;\n");
      out.write("            velocity.xy -= vec2(R - L, T - B);\n");
      out.write("            gl_FragColor = vec4(velocity, 0., 1.);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("    <script type=\"x-shader/x-fragment\" id=\"fragShaderPoint\">\n");
      out.write("        precision highp float;\n");
      out.write("        precision highp sampler2D;\n");
      out.write("    \n");
      out.write("        varying vec2 vUv;\n");
      out.write("        uniform sampler2D u_input_txr;\n");
      out.write("        uniform float u_ratio;\n");
      out.write("        uniform vec3 u_point_value;\n");
      out.write("        uniform vec2 u_point;\n");
      out.write("        uniform float u_point_size;\n");
      out.write("    \n");
      out.write("        void main () {\n");
      out.write("            vec2 p = vUv - u_point.xy;\n");
      out.write("            p.x *= u_ratio;\n");
      out.write("            vec3 splat = pow(2., -dot(p, p) / u_point_size) * u_point_value;\n");
      out.write("            vec3 base = texture2D(u_input_txr, vUv).xyz;\n");
      out.write("            gl_FragColor = vec4(base + splat, 1.);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("    <script type=\"x-shader/x-fragment\" id=\"fragShaderDisplay\">\n");
      out.write("        precision highp float;\n");
      out.write("        precision highp sampler2D;\n");
      out.write("    \n");
      out.write("        varying vec2 vUv;\n");
      out.write("        uniform sampler2D u_output_texture;\n");
      out.write("    \n");
      out.write("        void main () {\n");
      out.write("            vec3 C = texture2D(u_output_texture, vUv).rgb;\n");
      out.write("            float a = max(C.r, max(C.g, C.b));\n");
      out.write("            a = pow(.1 * a, .1);\n");
      out.write("            a = clamp(a, 0., 1.);\n");
      out.write("            gl_FragColor = vec4(1. - C, 1. - a);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    <script>\n");
      out.write("        const canvas = document.getElementsByTagName(\"canvas\")[0];\n");
      out.write("const image = document.getElementsByTagName(\"img\")[0];\n");
      out.write("canvas.width = canvas.clientWidth;\n");
      out.write("canvas.height = canvas.clientHeight;\n");
      out.write("\n");
      out.write("const params = {\n");
      out.write("    SIM_RESOLUTION: 128,\n");
      out.write("    DYE_RESOLUTION: 1024,\n");
      out.write("    DENSITY_DISSIPATION: .995,\n");
      out.write("    VELOCITY_DISSIPATION: .9,\n");
      out.write("    PRESSURE_ITERATIONS: 10,\n");
      out.write("    SPLAT_RADIUS: 3 / window.innerHeight,\n");
      out.write("    color: {r: .8, g: .5, b: .2}\n");
      out.write("};\n");
      out.write("\n");
      out.write("const pointer = {\n");
      out.write("    x: .65 * window.innerWidth,\n");
      out.write("    y: .5 * window.innerHeight,\n");
      out.write("    dx: 0,\n");
      out.write("    dy: 0,\n");
      out.write("    moved: false,\n");
      out.write("    firstMove: false // for codepen preview\n");
      out.write("};\n");
      out.write("window.setTimeout(() => {\n");
      out.write("    pointer.firstMove = true;\n");
      out.write("}, 3000);\n");
      out.write("\n");
      out.write("let prevTimestamp = Date.now();\n");
      out.write("\n");
      out.write("const gl = canvas.getContext(\"webgl\");\n");
      out.write("gl.getExtension(\"OES_texture_float\");\n");
      out.write("\n");
      out.write("\n");
      out.write("let outputColor, velocity, divergence, pressure;\n");
      out.write("\n");
      out.write("const vertexShader = createShader(\n");
      out.write("    document.getElementById(\"vertShader\").innerHTML,\n");
      out.write("    gl.VERTEX_SHADER);\n");
      out.write("\n");
      out.write("const splatProgram = createProgram(\"fragShaderPoint\");\n");
      out.write("const divergenceProgram = createProgram(\"fragShaderDivergence\");\n");
      out.write("const pressureProgram = createProgram(\"fragShaderPressure\");\n");
      out.write("const gradientSubtractProgram = createProgram(\"fragShaderGradientSubtract\");\n");
      out.write("const advectionProgram = createProgram(\"fragShaderAdvection\");\n");
      out.write("const displayProgram = createProgram(\"fragShaderDisplay\");\n");
      out.write("\n");
      out.write("\n");
      out.write("initFBOs();\n");
      out.write("render();\n");
      out.write("image.style.opacity = \"1\";\n");
      out.write("\n");
      out.write("\n");
      out.write("window.addEventListener(\"resize\", () => {\n");
      out.write("    params.SPLAT_RADIUS = 5 / window.innerHeight;\n");
      out.write("    canvas.width = canvas.clientWidth;\n");
      out.write("    canvas.height = canvas.clientHeight;\n");
      out.write("});\n");
      out.write("\n");
      out.write("canvas.addEventListener(\"click\", (e) => {\n");
      out.write("    pointer.dx = 10;\n");
      out.write("    pointer.dy = 10;\n");
      out.write("    pointer.x = e.pageX;\n");
      out.write("    pointer.y = e.pageY;\n");
      out.write("    pointer.firstMove = true;\n");
      out.write("});\n");
      out.write("\n");
      out.write("canvas.addEventListener(\"mousemove\", (e) => {\n");
      out.write("    pointer.moved = true;\n");
      out.write("    pointer.dx = 5 * (e.pageX - pointer.x);\n");
      out.write("    pointer.dy = 5 * (e.pageY - pointer.y);\n");
      out.write("    pointer.x = e.pageX;\n");
      out.write("    pointer.y = e.pageY;\n");
      out.write("    pointer.firstMove = true;\n");
      out.write("});\n");
      out.write("\n");
      out.write("canvas.addEventListener(\"touchmove\", (e) => {\n");
      out.write("    e.preventDefault();\n");
      out.write("    pointer.moved = true;\n");
      out.write("    pointer.dx = 8 * (e.targetTouches[0].pageX - pointer.x);\n");
      out.write("    pointer.dy = 8 * (e.targetTouches[0].pageY - pointer.y);\n");
      out.write("    pointer.x = e.targetTouches[0].pageX;\n");
      out.write("    pointer.y = e.targetTouches[0].pageY;\n");
      out.write("    pointer.firstMove = true;\n");
      out.write("});\n");
      out.write("\n");
      out.write("function createProgram(elId) {\n");
      out.write("    const shader = createShader(\n");
      out.write("        document.getElementById(elId).innerHTML,\n");
      out.write("        gl.FRAGMENT_SHADER);\n");
      out.write("    const program = createShaderProgram(vertexShader, shader);\n");
      out.write("    const uniforms = getUniforms(program);\n");
      out.write("    return {\n");
      out.write("        program, uniforms\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function createShaderProgram(vertexShader, fragmentShader) {\n");
      out.write("    const program = gl.createProgram();\n");
      out.write("    gl.attachShader(program, vertexShader);\n");
      out.write("    gl.attachShader(program, fragmentShader);\n");
      out.write("    gl.linkProgram(program);\n");
      out.write("\n");
      out.write("    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {\n");
      out.write("        console.error(\"Unable to initialize the shader program: \" + gl.getProgramInfoLog(program));\n");
      out.write("        return null;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    return program;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function getUniforms(program) {\n");
      out.write("    let uniforms = [];\n");
      out.write("    let uniformCount = gl.getProgramParameter(program, gl.ACTIVE_UNIFORMS);\n");
      out.write("    for (let i = 0; i < uniformCount; i++) {\n");
      out.write("        let uniformName = gl.getActiveUniform(program, i).name;\n");
      out.write("        uniforms[uniformName] = gl.getUniformLocation(program, uniformName);\n");
      out.write("    }\n");
      out.write("    return uniforms;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function createShader(sourceCode, type) {\n");
      out.write("    const shader = gl.createShader(type);\n");
      out.write("    gl.shaderSource(shader, sourceCode);\n");
      out.write("    gl.compileShader(shader);\n");
      out.write("\n");
      out.write("    if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {\n");
      out.write("        console.error(\"An error occurred compiling the shaders: \" + gl.getShaderInfoLog(shader));\n");
      out.write("        gl.deleteShader(shader);\n");
      out.write("        return null;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    return shader;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function blit(target) {\n");
      out.write("    gl.bindBuffer(gl.ARRAY_BUFFER, gl.createBuffer());\n");
      out.write("    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([\n");
      out.write("        -1, -1,\n");
      out.write("        -1, 1,\n");
      out.write("        1, 1,\n");
      out.write("        1, -1\n");
      out.write("    ]), gl.STATIC_DRAW);\n");
      out.write("    gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, gl.createBuffer());\n");
      out.write("    gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, new Uint16Array([0, 1, 2, 0, 2, 3]), gl.STATIC_DRAW);\n");
      out.write("    gl.vertexAttribPointer(0, 2, gl.FLOAT, false, 0, 0);\n");
      out.write("    gl.enableVertexAttribArray(0);\n");
      out.write("\n");
      out.write("    if (target == null) {\n");
      out.write("        gl.viewport(0, 0, gl.drawingBufferWidth, gl.drawingBufferHeight);\n");
      out.write("        gl.bindFramebuffer(gl.FRAMEBUFFER, null);\n");
      out.write("    } else {\n");
      out.write("        gl.viewport(0, 0, target.width, target.height);\n");
      out.write("        gl.bindFramebuffer(gl.FRAMEBUFFER, target.fbo);\n");
      out.write("    }\n");
      out.write("    gl.drawElements(gl.TRIANGLES, 6, gl.UNSIGNED_SHORT, 0);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function initFBOs() {\n");
      out.write("    const simRes = getResolution(params.SIM_RESOLUTION);\n");
      out.write("    const dyeRes = getResolution(params.DYE_RESOLUTION);\n");
      out.write("\n");
      out.write("    outputColor = createDoubleFBO(dyeRes.width, dyeRes.height);\n");
      out.write("    velocity = createDoubleFBO(simRes.width, simRes.height);\n");
      out.write("    divergence = createFBO(simRes.width, simRes.height, gl.RGB);\n");
      out.write("    pressure = createDoubleFBO(simRes.width, simRes.height, gl.RGB);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function getResolution(resolution) {\n");
      out.write("    let aspectRatio = gl.drawingBufferWidth / gl.drawingBufferHeight;\n");
      out.write("    if (aspectRatio < 1)\n");
      out.write("        aspectRatio = 1. / aspectRatio;\n");
      out.write("\n");
      out.write("    let min = Math.round(resolution);\n");
      out.write("    let max = Math.round(resolution * aspectRatio);\n");
      out.write("\n");
      out.write("    if (gl.drawingBufferWidth > gl.drawingBufferHeight)\n");
      out.write("        return {width: max, height: min};\n");
      out.write("    else\n");
      out.write("        return {width: min, height: max};\n");
      out.write("}\n");
      out.write("\n");
      out.write("function createFBO(w, h, type = gl.RGBA) {\n");
      out.write("    gl.activeTexture(gl.TEXTURE0);\n");
      out.write("\n");
      out.write("    const texture = gl.createTexture();\n");
      out.write("    gl.bindTexture(gl.TEXTURE_2D, texture);\n");
      out.write("    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);\n");
      out.write("    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);\n");
      out.write("    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);\n");
      out.write("    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);\n");
      out.write("    gl.texImage2D(gl.TEXTURE_2D, 0, type, w, h, 0, type, gl.FLOAT, null);\n");
      out.write("\n");
      out.write("    const fbo = gl.createFramebuffer();\n");
      out.write("    gl.bindFramebuffer(gl.FRAMEBUFFER, fbo);\n");
      out.write("    gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, texture, 0);\n");
      out.write("    gl.viewport(0, 0, w, h);\n");
      out.write("    gl.clear(gl.COLOR_BUFFER_BIT);\n");
      out.write("\n");
      out.write("    return {\n");
      out.write("        fbo,\n");
      out.write("        width: w,\n");
      out.write("        height: h,\n");
      out.write("        attach(id) {\n");
      out.write("            gl.activeTexture(gl.TEXTURE0 + id);\n");
      out.write("            gl.bindTexture(gl.TEXTURE_2D, texture);\n");
      out.write("            return id;\n");
      out.write("        }\n");
      out.write("    };\n");
      out.write("}\n");
      out.write("\n");
      out.write("function createDoubleFBO(w, h, type) {\n");
      out.write("    let fbo1 = createFBO(w, h, type);\n");
      out.write("    let fbo2 = createFBO(w, h, type);\n");
      out.write("\n");
      out.write("    return {\n");
      out.write("        width: w,\n");
      out.write("        height: h,\n");
      out.write("        texelSizeX: 1. / w,\n");
      out.write("        texelSizeY: 1. / h,\n");
      out.write("        read: () => {\n");
      out.write("            return fbo1;\n");
      out.write("        },\n");
      out.write("        write: () => {\n");
      out.write("            return fbo2;\n");
      out.write("        },\n");
      out.write("        swap() {\n");
      out.write("            let temp = fbo1;\n");
      out.write("            fbo1 = fbo2;\n");
      out.write("            fbo2 = temp;\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function render() {\n");
      out.write("    const dt = (Date.now() - prevTimestamp) / 1000;\n");
      out.write("    prevTimestamp = Date.now();\n");
      out.write("\n");
      out.write("    if (!pointer.firstMove) {\n");
      out.write("        pointer.moved = true;\n");
      out.write("        const newX = (.65 + .2 * Math.cos(.006 * prevTimestamp) * Math.sin(.008 * prevTimestamp)) * window.innerWidth;\n");
      out.write("        const newY = (.5 + .12 * Math.sin(.01 * prevTimestamp)) * window.innerHeight;\n");
      out.write("        pointer.dx = 10 * (newX - pointer.x);\n");
      out.write("        pointer.dy = 10 * (newY - pointer.y);\n");
      out.write("        pointer.x = newX;\n");
      out.write("        pointer.y = newY;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    if (pointer.moved) {\n");
      out.write("        pointer.moved = false;\n");
      out.write("\n");
      out.write("        gl.useProgram(splatProgram.program);\n");
      out.write("        gl.uniform1i(splatProgram.uniforms.u_input_txr, velocity.read().attach(0));\n");
      out.write("        gl.uniform1f(splatProgram.uniforms.u_ratio, canvas.width / canvas.height);\n");
      out.write("        gl.uniform2f(splatProgram.uniforms.u_point, pointer.x / canvas.width, 1 - pointer.y / canvas.height);\n");
      out.write("        gl.uniform3f(splatProgram.uniforms.u_point_value, pointer.dx, -pointer.dy, 1);\n");
      out.write("        gl.uniform1f(splatProgram.uniforms.u_point_size, params.SPLAT_RADIUS);\n");
      out.write("\n");
      out.write("        blit(velocity.write());\n");
      out.write("        velocity.swap();\n");
      out.write("\n");
      out.write("        gl.uniform1i(splatProgram.uniforms.u_input_txr, outputColor.read().attach(0));\n");
      out.write("        gl.uniform3f(splatProgram.uniforms.u_point_value, 1. - params.color.r, 1. - params.color.g, 1. - params.color.b);\n");
      out.write("        blit(outputColor.write());\n");
      out.write("        outputColor.swap();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    gl.useProgram(divergenceProgram.program);\n");
      out.write("    gl.uniform2f(divergenceProgram.uniforms.u_vertex_texel, velocity.texelSizeX, velocity.texelSizeY);\n");
      out.write("    gl.uniform1i(divergenceProgram.uniforms.u_velocity_txr, velocity.read().attach(0));\n");
      out.write("    blit(divergence);\n");
      out.write("\n");
      out.write("    gl.useProgram(pressureProgram.program);\n");
      out.write("    gl.uniform2f(pressureProgram.uniforms.u_vertex_texel, velocity.texelSizeX, velocity.texelSizeY);\n");
      out.write("    gl.uniform1i(pressureProgram.uniforms.u_divergence_txr, divergence.attach(0));\n");
      out.write("    for (let i = 0; i < params.PRESSURE_ITERATIONS; i++) {\n");
      out.write("        gl.uniform1i(pressureProgram.uniforms.u_pressure_txr, pressure.read().attach(1));\n");
      out.write("        blit(pressure.write());\n");
      out.write("        pressure.swap();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    gl.useProgram(gradientSubtractProgram.program);\n");
      out.write("    gl.uniform2f(gradientSubtractProgram.uniforms.u_vertex_texel, velocity.texelSizeX, velocity.texelSizeY);\n");
      out.write("    gl.uniform1i(gradientSubtractProgram.uniforms.u_pressure_txr, pressure.read().attach(0));\n");
      out.write("    gl.uniform1i(gradientSubtractProgram.uniforms.u_velocity_txr, velocity.read().attach(1));\n");
      out.write("    blit(velocity.write());\n");
      out.write("    velocity.swap();\n");
      out.write("\n");
      out.write("    gl.useProgram(advectionProgram.program);\n");
      out.write("    gl.uniform2f(advectionProgram.uniforms.u_vertex_texel, velocity.texelSizeX, velocity.texelSizeY);\n");
      out.write("    gl.uniform2f(advectionProgram.uniforms.u_output_textel, velocity.texelSizeX, velocity.texelSizeY);\n");
      out.write("\n");
      out.write("    gl.uniform1i(advectionProgram.uniforms.u_velocity_txr, velocity.read().attach(0));\n");
      out.write("    gl.uniform1i(advectionProgram.uniforms.u_input_txr, velocity.read().attach(0));\n");
      out.write("    gl.uniform1f(advectionProgram.uniforms.u_dt, dt);\n");
      out.write("    gl.uniform1f(advectionProgram.uniforms.u_dissipation, params.VELOCITY_DISSIPATION);\n");
      out.write("    blit(velocity.write());\n");
      out.write("    velocity.swap();\n");
      out.write("\n");
      out.write("    gl.uniform2f(advectionProgram.uniforms.u_output_textel, outputColor.texelSizeX, outputColor.texelSizeY);\n");
      out.write("    gl.uniform1i(advectionProgram.uniforms.u_velocity_txr, velocity.read().attach(0));\n");
      out.write("    gl.uniform1i(advectionProgram.uniforms.u_input_txr, outputColor.read().attach(1));\n");
      out.write("    gl.uniform1f(advectionProgram.uniforms.u_dissipation, params.DENSITY_DISSIPATION);\n");
      out.write("    blit(outputColor.write());\n");
      out.write("    outputColor.swap();\n");
      out.write("\n");
      out.write("    gl.useProgram(displayProgram.program);\n");
      out.write("    gl.uniform1i(displayProgram.uniforms.u_output_texture, outputColor.read().attach(0));\n");
      out.write("    blit();\n");
      out.write("\n");
      out.write("    requestAnimationFrame(render);\n");
      out.write("}\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
